// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetStream(ctx context.Context, id uuid.UUID) (Stream, error)
	InsertEvents(ctx context.Context, arg []InsertEventsParams) *InsertEventsBatchResults
	ListEventsByAggregateID(ctx context.Context, aggregateID uuid.UUID) ([]Event, error)
	ListEventsByAggregateIDAndVersion(ctx context.Context, arg ListEventsByAggregateIDAndVersionParams) ([]Event, error)
	UpsertSteam(ctx context.Context, arg UpsertSteamParams) error
}

var _ Querier = (*Queries)(nil)
